# Generated by Django 4.0 on 2021-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
