# Generated by Django 4.0 on 2021-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone_number', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
                ('roles', models.CharField(default='01', max_length=2)),
            ],
        ),
    ]
